# Generated by Django 3.0.6 on 2020-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20)),
                ('x', models.FloatField(max_length=30)),
                ('y', models.FloatField(max_length=30)),
                ('G2', models.BooleanField()),
                ('G3', models.BooleanField()),
                ('G4', models.BooleanField()),
            ],
        ),
    ]
